In [3]:
import numpy as np

## Vectorization

In [4]:
# addition
x = np.array([1,2,4])
y = np.array([5,7,9])

In [6]:
x+10

array([11, 12, 14])

In [7]:
x+y

array([ 6,  9, 13])

In [8]:
np.array_equal(x,y)

False

In [10]:
# boradcasting
a1 = np.array([[1,2],[3,4]])
s = np.array([5,6])

In [11]:
a1+s

array([[ 6,  8],
       [ 8, 10]])

In [12]:
# cross product and dot product
a2 = np.array([[5,6],[7,8]])

In [13]:
# cross product
a1*a2

array([[ 5, 12],
       [21, 32]])

In [14]:
# dot product
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [16]:
a = np.array([1,1,2,2,2,2,3,3,3,4,4,5,6,7,8,15,20])

In [17]:
np.mean(a)

5.176470588235294

In [18]:
np.median(a)

3.0

In [19]:
q1 = np.quantile(a, 0.25)

In [25]:
q3= np.quantile(a, 0.75)

In [26]:
q1

2.0

In [27]:
q3

6.0

In [29]:
iqr = q3-q1
iqr

4.0

In [30]:
upper_whisker = q3+iqr*1.5
lower_whisker = q1-iqr*1.5

In [31]:
upper_whisker

12.0

In [32]:
lower_whisker

-4.0

In [33]:
# reduce skewness
from scipy.stats import skew
# -0.5 to 0.5 is normal distribution
# < -0.5 is Negative skew
# > 0.5 is Positive skew
skew(a)

1.8776083354064455

In [35]:
b = np.sqrt(a)
skew(b)

1.2211351116052678

In [36]:
c = np.cbrt(a)
skew(c)

0.9566641733549022

In [39]:
d = np.log(a)
skew(d)

0.38482036573141176

In [41]:
x = np.arange(10,30,2).reshape(5,2)
x

array([[10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28]])

In [42]:
x.transpose()

array([[10, 14, 18, 22, 26],
       [12, 16, 20, 24, 28]])

In [43]:
x.flatten()

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])